test artifacts ifpen_el8_gimkl-2021b.yml

diff --git a/.github/workflows/ifpen_el8_gimkl-2021b.yml b/.github/workflows/ifpen_el8_gimkl-2021b.yml
--- a/.github/workflows/ifpen_el8_gimkl-2021b.yml
+++ b/.github/workflows/ifpen_el8_gimkl-2021b.yml
@@ -69,90 +69,101 @@ jobs:
 
       # Installation
 
-      - name: Checkout
-        id: checkout
-        if: |
-          (success() || failure())
-        uses: actions/checkout@v5
-        with:
-          path: ${{ env.SOURCE_DIR }}
-          submodules: true
+#      - name: Checkout
+#        id: checkout
+#        if: |
+#          (success() || failure())
+#        uses: actions/checkout@v5
+#        with:
+#          path: ${{ env.SOURCE_DIR }}
+#          submodules: true
+#
+#      - name: Modules information
+#        id: modules_information
+#        if: |
+#          (success() || failure()) &&
+#          steps.checkout.outcome == 'success'
+#        shell: bash
+#        run: module --terse list 2>&1 | sort
+#
+#      - name: Configure
+#        id: configure
+#        if: |
+#          (success() || failure()) &&
+#          steps.checkout.outcome == 'success'
+#        shell: bash
+#        run: cmake -S ${{ env.SOURCE_DIR }} -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} ${{ env.CM_CCACHE_OPTS }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DARCCORE_BUILD_MODE=Check -DREMOVE_UID_ON_DETACH=ON -DUSE_GTEST_DEATH_TEST=ON -DCMAKE_DISABLE_FIND_PACKAGE_Papi=ON -DALIEN_BUILD_COMPONENT=all -DALIEN_PLUGIN_HYPRE=ON -DALIEN_PLUGIN_PETSC=ON -DUSE_GRAPH_CONNECTIVITY_POLICY=ON -DARCANE_DISABLE_PERFCOUNTER_TESTS=ON
+#
+#      - name: Build
+#        id: build
+#        if: |
+#          (success() || failure()) &&
+#          steps.configure.outcome == 'success'
+#        shell: bash
+#        run: cmake --build ${{ env.BUILD_DIR }} ${{ env.CM_BUILD_OPTS }}
+#
+#      - name: Install
+#        id: install
+#        if: |
+#          (success() || failure()) &&
+#          steps.build.outcome == 'success'
+#        shell: bash
+#        run: cmake --install ${{ env.BUILD_DIR }}
+#
+#      - name: Test
+#        id: test
+#        if: |
+#          (success() || failure()) &&
+#          steps.build.outcome == 'success'
+#        shell: bash
+#        run: |
+#           # Force using intel-mpi 2021.16
+#           chmod -R u+w ${EBROOTIMPI}
+#           mv ${EBROOTIMPI} ${EBROOTIMPI}.old
+#           ln -s /opt/intel-mpi ${EBROOTIMPI}
+#           ln -s latest ${EBROOTIMPI}/mpi/2021.4.0
+#           # Check intel-mpi version
+#           which mpiexec
+#           mpiexec --version
+#           # Run test
+#           ctest --test-dir ${{ env.BUILD_DIR }} ${{ env.CT_OPTS }}
+#
+#      - name: Upload test artifact
+#        id: upload-test-artifact
+#        uses: actions/upload-artifact@v4
+#        if: |
+#          (success() || failure()) &&
+#          steps.test.outcome == 'failure'
+#        with:
+#          name: test-artifact
+#          path: ${{ env.BUILD_DIR }}/Testing
+#          retention-days: 1
+#          include-hidden-files: true
+#
+#      - name: Save cache
+#        id: save-cache
+#        if: |
+#          (success() || failure()) &&
+#          steps.build.outcome == 'success'
+#        uses: actions/cache/save@v4
+#        with:
+#          path: ${{ env.CCACHE_DIR }}
+#          key:  ${{ steps.restore-cache.outputs.cache-primary-key }}
+#
+#      - name: Clean
+#        id: clean
+#        if: always()
+#        run: |
+#           rm -rf ${{ env.SOURCE_DIR }}
+#           ls -l /__w/framework/framework
 
-      - name: Modules information
-        id: modules_information
-        if: |
-          (success() || failure()) &&
-          steps.checkout.outcome == 'success'
-        shell: bash
-        run: module --terse list 2>&1 | sort
-
-      - name: Configure
-        id: configure
-        if: |
-          (success() || failure()) &&
-          steps.checkout.outcome == 'success'
-        shell: bash
-        run: cmake -S ${{ env.SOURCE_DIR }} -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} ${{ env.CM_CCACHE_OPTS }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DARCCORE_BUILD_MODE=Check -DREMOVE_UID_ON_DETACH=ON -DUSE_GTEST_DEATH_TEST=ON -DCMAKE_DISABLE_FIND_PACKAGE_Papi=ON -DALIEN_BUILD_COMPONENT=all -DALIEN_PLUGIN_HYPRE=ON -DALIEN_PLUGIN_PETSC=ON -DUSE_GRAPH_CONNECTIVITY_POLICY=ON -DARCANE_DISABLE_PERFCOUNTER_TESTS=ON
-
-      - name: Build
-        id: build
-        if: |
-          (success() || failure()) &&
-          steps.configure.outcome == 'success'
-        shell: bash
-        run: cmake --build ${{ env.BUILD_DIR }} ${{ env.CM_BUILD_OPTS }}
-
-      - name: Install
-        id: install
-        if: |
-          (success() || failure()) &&
-          steps.build.outcome == 'success'
-        shell: bash
-        run: cmake --install ${{ env.BUILD_DIR }}
-
-      - name: Test
-        id: test
-        if: |
-          (success() || failure()) &&
-          steps.build.outcome == 'success'
-        shell: bash
+      - name: Upload artifact manually
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-           # Force using intel-mpi 2021.16
-           chmod -R u+w ${EBROOTIMPI}
-           mv ${EBROOTIMPI} ${EBROOTIMPI}.old
-           ln -s /opt/intel-mpi ${EBROOTIMPI}
-           ln -s latest ${EBROOTIMPI}/mpi/2021.4.0
-           # Check intel-mpi version
-           which mpiexec
-           mpiexec --version
-           # Run test
-           ctest --test-dir ${{ env.BUILD_DIR }} ${{ env.CT_OPTS }}
-
-      - name: Upload test artifact
-        id: upload-test-artifact
-        uses: actions/upload-artifact@v4
-        if: |
-          (success() || failure()) &&
-          steps.test.outcome == 'failure'
-        with:
-          name: test-artifact
-          path: ${{ env.BUILD_DIR }}/Testing
-          retention-days: 1
-          include-hidden-files: true
-
-      - name: Save cache
-        id: save-cache
-        if: |
-          (success() || failure()) &&
-          steps.build.outcome == 'success'
-        uses: actions/cache/save@v4
-        with:
-          path: ${{ env.CCACHE_DIR }}
-          key:  ${{ steps.restore-cache.outputs.cache-primary-key }}
-
-      - name: Clean
-        id: clean
-        if: always()
-        run: |
-           rm -rf ${{ env.SOURCE_DIR }}
-           ls -l /__w/framework/framework
+          echo "OK" > /tmp/OK.txt
+          tar czf /tmp/test-results.tar.gz /tmp/OK.txt
+          curl -H "Authorization: Bearer $GITHUB_TOKEN" \
+               -H "Content-Type: application/gzip" \
+               --data-binary @/tmp/test-results.tar.gz \
+               "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/actions/artifacts"
