WIP Check IPFEN failure in workflow

diff --git a/.github/workflows/ifpen_gimkl_2018b.yml b/.github/workflows/ifpen_gimkl_2018b.yml
--- a/.github/workflows/ifpen_gimkl_2018b.yml
+++ b/.github/workflows/ifpen_gimkl_2018b.yml
@@ -106,13 +106,13 @@ jobs:
         shell: bash
         run: cmake --install ${{ env.BUILD_DIR }}
 
-      - name: Test
-        id: test
-        if: |
-          (success() || failure()) &&
-          steps.build.outcome == 'success'
-        shell: bash
-        run: ctest --test-dir ${{ env.BUILD_DIR }} ${{ env.CT_OPTS }} -E '^hydro5_4proc_3sd_4proc$'
+      # - name: Test
+      #   id: test
+      #   if: |
+      #     (success() || failure()) &&
+      #     steps.build.outcome == 'success'
+      #   shell: bash
+      #   run: ctest --test-dir ${{ env.BUILD_DIR }} ${{ env.CT_OPTS }} -R "refmvhandlers.scalar.Direct" -V
 
       - name: Upload test artifact
         id: upload-test-artifact
